### ISSUE TITLE
After 10-20 seconds in singleplayer, framerate drops from a smooth 60 to <10.

### ISSUE THREAD

**Issue by Qix-** [Unarelith/OpenMiner#95] opened 2020-04-29 22:29 UTC
Title.

Further, the FPS counter shows 60 (correctly) until the lag hits, at which point it oscillates between 50 and 80 - none of which is correct, as it's barely getting 10 frames a second.

I'm on MacOS mojave:

```
clang version 10.0.0 (https://github.com/llvm/llvm-project d32170dbd5b0d54436537b6b75beaf44324e0c28)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /usr/local/bin
```

**Comment by Unarelith** [comment] 2020-04-29 22:48
Thanks for the report!

This is the first time someone actually runs OpenMiner on MacOS.
Unfortunately, since I don't have a MacOS system myself, that will be really hard to debug. :/

Do you have vsync enabled when experiencing this lag?

**Comment by Qix-** [comment] 2020-04-30 07:37
It was, yes, but this occurs with vsync on or off - doesn't seem to matter.

**Comment by Unarelith** [comment] 2020-04-30 15:31
Ok so vsync was enabled and you got more than 60fps.. Is your monitor able and configured to display more than 60fps?

I think there's another big problem tho, the FPS counter should be quite accurate because it's basically counting the frames that were displayed during the last second...

**Comment by Qix-** [comment] 2020-05-01 10:49
I think there's a misunderstanding; let me clarify.

With vsync on (which was the default for me), I was getting a solid 60 fps. However, after about 10 seconds, framerate drops to maybe 10-20 FPS. However, the FPS counter reports _higher_ than 60 FPS (there's definitely a bug with the FPS counter).

The same problem occurs even with vsync disabled.

**Comment by Unarelith** [comment] 2020-05-01 15:24
Could you come on the Discord server please?

I'd need your help to debug this issue, because I can't reproduce it on any of my systems..

**Comment by Unarelith** [comment] 2020-07-02 17:23
@Qix- 

I just tried OpenMiner on a 2013 11'' Macbook Air running macOS Catalina, and it worked quite well considering the limitations of the machine.

The Mac I tested had those specs:
- 1.3 GHz Intel Core i5 dual-core
- 4 Go 1600 MHz DDR3
- Intel HD Graphics 5000 1536 Mo

With that machine I have ~40 FPS when loading the world, and a 50-60 FPS most of the time.
Also, the FPS counter seems reliable.

What kind of Mac do you have?

Also, maybe the issue has been fixed meanwhile so could you try lastest commit please?

**Comment by Unarelith** [comment] 2020-07-06 13:31
Well until I get an answer from you I'm going to close this.

The FPS counter counts the amount of frames sent to the OS for display, so it should be accurate... unless the OS itself (or some program) discards some frames.
When using `xcompmgr` on Linux, I get 30 fps but the counter displays 60 fps. That's because `xcompmgr` somehow discards frame itself, so my program thinks it runs at 60 fps but the OS actually renders 30 fps.
Killing `xcompmgr` fixes this issue, maybe it's similar for you?

**Closed by Unarelith** 2020-07-06 13:31 UTC
Labels: Bug, MacOS
